### ISSUE TITLE
ERROR: Exception in ASGI application

### ISSUE THREAD

**Issue by defender107** [eideehi/sd-webui-better-prompt#17]
Hey,
Since I updated automatic1111 I receive an error message in the console. I disabled all other plugins.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "J:\diffusion\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "J:\diffusion\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "J:\diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "J:\diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "J:\diffusion\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "J:\diffusion\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "J:\diffusion\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 137, in get_extra_networks
    {"name": item["name"], "preview": item["preview"], "search_term": item["search_term"]})
KeyError: 'search_term'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "J:\diffusion\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "J:\diffusion\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "J:\diffusion\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "J:\diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "J:\diffusion\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "J:\diffusion\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "J:\diffusion\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "J:\diffusion\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "J:\diffusion\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 144, in get_extra_networks
    {"name": item["name"], "preview": item["preview"], "search_term": item["search_term"]})
KeyError: 'search_term'

**Comment by takayama-rado** [comment]
Hello.
I encountered the same error.
I think this is due to the recent update of [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0726a6e12e85a37d1e514f5603acf9f058c11783).

I updated "sd-webui-better-prompt/scripts/better_prompt.py"  locally as follows, and the errors have disappeared.

Update lines 137 and 144
```python
# {"name": item["name"], "preview": item["preview"], "search_term": item["search_term"]}
{"name": item["name"], "preview": item["preview"], "search_term": item["search_terms"]}
```
