### ISSUE TITLE
Unable to detect git.exe on Windows system.

### ISSUE THREAD

**Issue by chenshaoju** [eideehi/sd-webui-better-prompt#2]
Sorry for my English.

Even though the git.exe environment is already in place on the Windows system, it still cannot be used properly. 

![GIF 2023-04-21 20-43-16](https://user-images.githubusercontent.com/515763/233639812-3cb832f5-781c-4d2f-91bc-82259e9a9b1d.gif)

```
Error loading script: better_prompt.py
Traceback (most recent call last):
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 240, in <module>
    initialize()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 235, in initialize
    print_version()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 105, in print_version
    result = subprocess.check_output([GIT, "log", '--pretty=v%(describe:tags)', "-n", "1"], cwd = EXTENSION_ROOT, shell = True).decode("utf-8")
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Software\\git\\bin\\git.exe', 'log', '--pretty=v%(describe:tags)', '-n', '1']' returned non-zero exit status 128.
```

Please let me know if there is any additional information that needs to be provided. 💖

Thank you.

**Comment by eideehi** [comment]
Please don't worry about the quality of your English. I'm also using a translation tool, so I'm in no position to criticize others.

I appreciate you for attaching a gif in addition to the error log. It is very helpful. In this script, getting the git path in the same way as the Web UI, but it seems that it doesn't work well in some environments. I will try to change the method of getting the git command.

**Comment by eideehi** [comment]
I changed the way to obtain git commands in version 0.2.0. If you still have the issue, please let us know.

**Comment by chenshaoju** [comment]
still not working... 😵

```
venv "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Installing sd-dynamic-prompts requirements.txt

Installing sd-webui-controlnet requirement: mediapipe==0.9.1.0
Installing sd-webui-controlnet requirement: opencv-python

Launching Web UI with arguments: --xformers --disable-nan-check --opt-sub-quad-attention --opt-split-attention --no-half-vae
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
fatal: not a git repository (or any of the parent directories): .git
Error loading script: better_prompt.py
Traceback (most recent call last):
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 251, in <module>
    initialize()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 246, in initialize
    print_version()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 114, in print_version
    result = subprocess.check_output([git, "log", '--pretty=v%(describe:tags)', "-n", "1"], cwd = EXTENSION_ROOT, shell = True).decode("utf-8")
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'log', '--pretty=v%(describe:tags)', '-n', '1']' returned non-zero exit status 128.

Loading weights [5493a0ec49] from D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\models\Stable-diffusion\AbyssOrangeMix3_AOM3A1B.safetensors
Creating model from config: D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\models\VAE\anything-v4.0.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(3): bad-hands-5, bad_prompt_version2, ng_deepnegative_v1_75t
Model loaded in 6.9s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.5s, load VAE: 0.5s, move model to device: 3.3s, load textual inversion embeddings: 1.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.0s (import torch: 1.7s, import gradio: 1.0s, import ldm: 0.6s, other imports: 0.9s, load scripts: 1.9s, load SD checkpoint: 7.0s, create ui: 0.5s, gradio launch: 0.1s).
fatal: not a git repository (or any of the parent directories): .git
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\applications.py", line 120, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await route.handle(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 206, in check_for_updates
    version = subprocess.check_output([git, "log", '--pretty=%(describe:tags)', "-n", "1"], cwd = EXTENSION_ROOT, shell = True).decode("utf-8")
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'log', '--pretty=%(describe:tags)', '-n', '1']' returned non-zero exit status 128.
```

**Comment by eideehi** [comment]
Could you please replace the "extensions\sd-webui-better-prompt\scripts\better_prompt.py" file with the attached file and then start the Web UI? When you start the Web UI, information such as the following will be displayed on the Web UI console. Please let me know the contents of that information.

==== Better Prompt Debug Start ====================================
scripts.basedir: E:\programs\stable-diffusion-webui-dev\extensions\sd-webui-better-prompt
EXTENSION_ROOT: E:\programs\stable-diffusion-webui-dev\extensions\sd-webui-better-prompt
==== Better Prompt Debug End ====================================

[better_prompt.zip](https://github.com/eideehi/sd-webui-better-prompt/files/11303259/better_prompt.zip)

**NOTE: I have archived the .py file into a zip file since I cannot attach it directly. Please unzip the file and extract the "better_prompt.py" file.**

**Comment by chenshaoju** [comment]
here is output:
```
==== Better Prompt Debug Start ====================================
scripts.basedir: D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt
EXTENSION_ROOT: D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt
inspect: D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py
==== Better Prompt Debug End ====================================
fatal: not a git repository (or any of the parent directories): .git
Error loading script: better_prompt.py
Traceback (most recent call last):
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 260, in <module>
    initialize()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 255, in initialize
    print_version()
  File "D:\Software\Python3.10\userfolder\stable-diffusion-webui-master\extensions\sd-webui-better-prompt\scripts\better_prompt.py", line 122, in print_version
    result = subprocess.check_output([git, "log", '--pretty=v%(describe:tags)', "-n", "1"], cwd = EXTENSION_ROOT, shell = True).decode("utf-8")
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Software\Python3.10\python-3.10.9.amd64\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'log', '--pretty=v%(describe:tags)', '-n', '1']' returned non-zero exit status 128.
```

**Comment by eideehi** [comment]
Thank you for your cooperation. The cause may have become clear.

The error message says that "extensions\sd-webui-better-prompt" is not a git repository. There is a possibility that the directory "extensions\sd-webui-better-prompt\\.git" does not exist for some reason.

Please try the following steps:
1. Delete the "extensions\sd-webui-better-prompt" directory.
2. Move to the "extensions" directory and run the command `git clone https://github.com/eideehi/sd-webui-better-prompt.git`
3. Make sure that "extensions\sd-webui-better-prompt" has been created.
4. Start the Web UI.
5. Please report the results.

**Comment by chenshaoju** [comment]
After downloading from git to the extensions directory, it worked properly. 

Due to some network issues in my country, git under the command prompt wasn't working well. Therefore, I downloaded the zip archive directly from GitHub and extracted it into the extensions directory. It looks like this was the problem. 

Thank you. 🍻
